server:
  port: 8090


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SirGian99/trialConfigServer
          default-label: config
  application:
    name: trialConfigServer

#spring.profiles.active: native
#spring.cloud.config.server.native.searchLocations: file:///${user.home}/Documents/projects/config
##spring.cloud.config.server.native.searchLocations: classpath:config/